"""empty message

Revision ID: f644166ed952
Revises: 44b80eae753a
Create Date: 2018-02-07 10:07:36.294642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f644166ed952'
down_revision = '44b80eae753a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('time_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'time_created')
    # ### end Alembic commands ###
